### ISSUE TITLE
Farming 0 Pokestops.... True? 

### ISSUE THREAD

**Issue by FunctionCode** [Panthere/GoBot#28]
With the seventh release, I've found an issue. I have "Collect pokestops" enabled but I always get "Farming 0 Pokestops... True" and am not collecting ANYTHING from any pokestops. Please look into this!

**Comment by Panthere** [comment]
This means that you are either softbanned or the servers are playing up.
I know you think that it is my bot because other bots will work fine but trust me, it's actually the servers.
Many people have had the same issues and stopping other bots and waiting a couple of minutes has seemed to fix the issue.
