### ISSUE TITLE
Turning item Recycling off.

### ISSUE THREAD

**Issue by steppeulv** [Panthere/GoBot#61]
Thanks for the great tool, I really appreciate the work!
I've changed item recycling numbers multiple times both whilst paused and when walking, but I've found that it just keeps recycling my pokeballs. Can I turn it off either in the files or some other way? And how exactly does recycling work?

**Comment by ExReservoir** [comment]
What is item recycling?

**Comment by Hunter926** [comment]
Just go to the items tab and set all the items to 350, since that's the default maximum number of items you can store. That will effectively disable item recycling.. Though I don't know why you would want to do this anyway.
However, if you do that your bag may become full of one item like pokeballs and not have any room to keep the great or ultra balls you get from pokestops / leveling up.

**Comment by Panthere** [comment]
Exactly as hunter said.
